id: P001771
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG2170
  title: སྙིང་ཐིག་སྔོན་འགྲོའི་ཁྲིད་ཡིག་ཐར་ལམ་གསལ་བྱེད་དང་ལམ་བཟང་ཡེ་ཤེས་སྙིང་པོ་བཅས།
  author: ''
  volumes:
    5cb95ad631904f19a772c90bd5b84edb:
      image_group_id: I1KG2189
      title: ''
      volume_number: 1
      total_pages: 304
      base_file: v001.txt
