id: I77D3A53A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T13:33:46+00:00'
last_modified: '2022-06-07T15:05:38.675122+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG2170
  title: སྙིང་ཐིག་སྔོན་འགྲོའི་ཁྲིད་ཡིག་ཐར་ལམ་གསལ་བྱེད་དང་ལམ་བཟང་ཡེ་ཤེས་སྙིང་པོ་བཅས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4B0C:
      image_group_id: I1KG2189
      title: ''
      total_pages: 304
      order: 1
      base_file: 4B0C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
